### ISSUE TITLE
user_tweets_parameters don't seem to be working.

### ISSUE THREAD

**Issue by bowenac** [digitoimistodude/dude-twitter-feed#1]
Parameters don't seem to be working for me.

Example
```
add_filter( 'dude-twitter-feed/user_tweets_parameters', function( $args ) {
  $args['count'] = 3;
  $args['include_rts'] = false;

  return $args;
});
```
Always returns 5 and also including retweets.

**Comment by rollecode** [comment]
Hello! Thanks for using our plugin. Have you removed the transient rows from database? This plugin uses WordPress built-in transients as cache, so the amount will only update after you remove those tweet related rows from wp-options table, or wait 10 minutes Twitter feed to update.

We have not yet implemented automatic emptying the cache if the settings have changed, so you have to use this manually at this time.
